import React, { useMemo, useState } from 'react';
import { format } from 'date-fns';
import { Search, Eye, Download, Trash2 } from 'lucide-react';
import { ReportHistoryEntry } from '../../types/report.types';
import { RepositoryPagination } from '../common/RepositoryPagination';

interface ReportHistoryTableProps {
  history: ReportHistoryEntry[];
  onView: (entry: ReportHistoryEntry) => void;
  onDownload: (entry: ReportHistoryEntry) => void;
  onDelete: (id: string) => void;
  canDelete: boolean;
}

const STATUS_STYLES: Record<string, string> = {
  completed: 'bg-jade/15 text-jade',
  failed: 'bg-red-500/15 text-red-400',
};

export function ReportHistoryTable({ history, onView, onDownload, onDelete, canDelete }: ReportHistoryTableProps) {
  const [search, setSearch] = useState('');
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(15);

  const filtered = useMemo(() => {
    if (!search.trim()) return history;
    const term = search.trim().toLowerCase();
    return history.filter((h) =>
      h.reportName.toLowerCase().includes(term) ||
      h.reportType.toLowerCase().includes(term) ||
      h.generatedBy.toLowerCase().includes(term)
    );
  }, [history, search]);

  const total = filtered.length;
  const totalPages = Math.max(1, Math.ceil(total / pageSize));
  const clampedPage = Math.min(page, totalPages);
  const paginated = filtered.slice((clampedPage - 1) * pageSize, clampedPage * pageSize);

  return (
    <div className="bg-noir-700 border border-white/[0.06] rounded-xl p-5">
      <div className="flex items-center justify-between mb-4">
        <p className="font-display font-bold text-sm text-white/80">Report History</p>
        <div className="relative w-full max-w-xs">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-white/25" />
          <input
            type="text"
            value={search}
            onChange={(e) => { setSearch(e.target.value); setPage(1); }}
            placeholder="Search by name, type, or generated by…"
            className="w-full bg-noir-600 border border-white/[0.08] rounded-lg pl-9 pr-3 py-1.5 text-xs text-white/80 placeholder:text-white/25 focus:outline-none focus:border-jade transition-colors"
          />
        </div>
      </div>

      {total === 0 ? (
        <div className="text-center py-8 text-white/30 text-sm">No reports generated yet.</div>
      ) : (
        <>
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse min-w-[800px]">
              <thead>
                <tr className="border-b-2 border-white/[0.12]">
                  {['Report Name', 'Report Type', 'Generated By', 'Generated Date', 'Format', 'Status'].map((h) => (
                    <th key={h} className="px-3 py-2.5 text-[11px] font-semibold uppercase tracking-widest text-white/40 whitespace-nowrap">{h}</th>
                  ))}
                  <th className="px-3 py-2.5 text-[11px] font-semibold uppercase tracking-widest text-white/40 text-right">Actions</th>
                </tr>
              </thead>
              <tbody>
                {paginated.map((entry) => (
                  <tr key={entry.id} className="border-b border-white/[0.05] last:border-b-0 hover:bg-white/[0.03] transition-colors">
                    <td className="px-3 py-2.5 text-sm font-semibold text-white/85 whitespace-nowrap">{entry.reportName}</td>
                    <td className="px-3 py-2.5 text-xs text-white/55 whitespace-nowrap">{entry.reportType}</td>
                    <td className="px-3 py-2.5 text-xs text-white/55 whitespace-nowrap">{entry.generatedBy}</td>
                    <td className="px-3 py-2.5 text-xs text-white/45 whitespace-nowrap">{format(new Date(entry.generatedAt), 'MMM d, yyyy h:mm a')}</td>
                    <td className="px-3 py-2.5 text-xs text-white/45 uppercase whitespace-nowrap">{entry.exportFormat}</td>
                    <td className="px-3 py-2.5">
                      <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full uppercase tracking-wide ${STATUS_STYLES[entry.status]}`}>{entry.status}</span>
                    </td>
                    <td className="px-3 py-2.5">
                      <div className="flex items-center justify-end gap-1">
                        <button type="button" onClick={() => onView(entry)} title="View" className="p-1.5 rounded-lg text-white/40 hover:text-jade hover:bg-white/5 transition-colors"><Eye className="w-3.5 h-3.5" /></button>
                        <button type="button" onClick={() => onDownload(entry)} title="Download" className="p-1.5 rounded-lg text-white/40 hover:text-blue-400 hover:bg-white/5 transition-colors"><Download className="w-3.5 h-3.5" /></button>
                        {canDelete && (
                          <button type="button" onClick={() => onDelete(entry.id)} title="Delete" className="p-1.5 rounded-lg text-white/40 hover:text-red-400 hover:bg-white/5 transition-colors"><Trash2 className="w-3.5 h-3.5" /></button>
                        )}
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <RepositoryPagination page={clampedPage} pageSize={pageSize} total={total} onPageChange={setPage} onPageSizeChange={setPageSize} />
        </>
      )}
    </div>
  );
}
